{% set version = "0.4.8" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggvis
  version: {{ version|replace("-", "_") }}

source:
  fn: ggvis_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggvis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggvis/ggvis_{{ version }}.tar.gz
  sha256: 3d5480a0b97a57c26b595785f826b13d7695dab1f1dd8fcf5d7964fa8546a26a

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
  host:
    - r-base
    - r-assertthat
    - r-dplyr >=0.4.0
    - r-htmltools >=0.2.4
    - r-jsonlite >=0.9.11
    - r-lazyeval
    - r-magrittr
    - r-shiny >=0.11.1
  run:
    - r-base
    - r-assertthat
    - r-dplyr >=0.4.0
    - r-htmltools >=0.2.4
    - r-jsonlite >=0.9.11
    - r-lazyeval
    - r-magrittr
    - r-shiny >=0.11.1

test:
  commands:
    - $R -e "library('ggvis')"           # [not win]
    - "\"%R%\" -e \"library('ggvis')\""  # [win]

about:
  home: http://ggvis.rstudio.com/
  license: GPL-2.0-only
  summary: An implementation of an interactive grammar of graphics, taking the best parts of 'ggplot2', combining them with the reactive framework of 'shiny' and drawing web graphics using 'vega'.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
