{% set version = "0.4.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggvis
  version: {{ version|replace("-", "_") }}

source:
  fn: ggvis_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/ggvis_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggvis/ggvis_{{ version }}.tar.gz
  sha256: 82373c3565c299279f6849f798cc39127b2b3f7ff2deee1946528474824b3124

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS, mgcv, lubridate, testthat (>= 0.8.1), knitr (>= 1.6), rmarkdown
requirements:
  build:
  host:
    - r-base
    - r-assertthat
    - r-dplyr >=0.4.0
    - r-htmltools >=0.2.4
    - r-jsonlite >=0.9.11
    - r-lazyeval
    - r-magrittr
    - r-shiny >=0.11.1

  run:
    - r-base
    - r-assertthat
    - r-dplyr >=0.4.0
    - r-htmltools >=0.2.4
    - r-jsonlite >=0.9.11
    - r-lazyeval
    - r-magrittr
    - r-shiny >=0.11.1

test:
  commands:
    - $R -e "library('ggvis')"           # [not win]
    - "\"%R%\" -e \"library('ggvis')\""  # [win]

about:
  home: http://ggvis.rstudio.com/
  license: GPL-2
  summary: An implementation of an interactive grammar of graphics, taking the best parts of
    'ggplot2', combining them with the reactive framework of 'shiny' and drawing web
    graphics using 'vega'.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
