{% set version = "0.4.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggvis
  version: {{ version|replace("-", "_") }}

source:
  fn: ggvis_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/ggvis_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/ggvis/ggvis_{{ version }}.tar.gz
  sha256: 1332ea122b768688c8a407a483be80febc4576de0ec8929077738421b27cafaf

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-assertthat
    - r-dplyr >=0.4.0
    - r-htmltools >=0.2.4
    - r-jsonlite >=0.9.11
    - r-lazyeval
    - r-magrittr
    - r-shiny >=0.11.1

  run:
    - r-base
    - r-assertthat
    - r-dplyr >=0.4.0
    - r-htmltools >=0.2.4
    - r-jsonlite >=0.9.11
    - r-lazyeval
    - r-magrittr
    - r-shiny >=0.11.1

test:
  commands:
    - $R -e "library('ggvis')"  # [not win]
    - "\"%R%\" -e \"library('ggvis')\""  # [win]

about:
  home: http://ggvis.rstudio.com/
  license: GPL-2
  summary: An implementation of an interactive grammar of graphics, taking the best parts of
    'ggplot2', combining them with the reactive framework of 'shiny' and drawing web
    graphics using 'vega'.
  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
