# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "DVyQbtVLn+q3RV6UQHndyiWixHJktpFzKaUyJ+8uJ2hADNXLF37ZnSyKpOwVodQZjqwLlI83m7R2+g1UURzqQZq2hTL/xrzJ14RLNFtZ6FV3o1ndA3kXIlyiL2A4BnQxfVbXHehKnlMaBpicYl2bHjed9rzXzPsVHNA1+O21VyAM13ZV9L5/6DD3thHEBre89hqBQ6DYA9c8pbn88yARYipObsXspDma1Z9v93ivGrguizumVtyf+kv39ltJjPSSKguzxtQfhQAih0m2+pt3PEyEIiYrxntknstLxgLPbqEmnj/sv2pFs4xfmOEpyzCsfBHn0K8Pi+ZZ1iUB/lGNK2tRMt0GMCUUKWkwdu9bL0SScHJ3yyfOV/NJMD34n1Vt0Q43qYRF9boogH6pW+4/8Pm4VsJ/357yQKxmV/goSt0ncDuJeIa3z1HE7MGc8dCsz5zNGXFUWMWTuMmVMFfvXf/H7Q4YU3WC+BWV3eX2qWiOVmeqcFFw3W/pKY6ZU1KqfXcs/gQSk1HKNd6LSONXyIsYq02ZFU9sxWPXUEtiuEeVAC7YaIgVvjttFpYOmPXIQZNN2W+FpoJiimc80c/6kJs29SXpyeZfa7C3HZyJpG6I6JnW1jzJIAuAL6IeQxkwDv8weiJXAkJElFikpbFX2+T0gDhO7up5l4QKsZ83vZ4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
