appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: DVyQbtVLn+q3RV6UQHndyiWixHJktpFzKaUyJ+8uJ2hADNXLF37ZnSyKpOwVodQZjqwLlI83m7R2+g1UURzqQZq2hTL/xrzJ14RLNFtZ6FV3o1ndA3kXIlyiL2A4BnQxfVbXHehKnlMaBpicYl2bHjed9rzXzPsVHNA1+O21VyAM13ZV9L5/6DD3thHEBre89hqBQ6DYA9c8pbn88yARYipObsXspDma1Z9v93ivGrguizumVtyf+kv39ltJjPSSKguzxtQfhQAih0m2+pt3PEyEIiYrxntknstLxgLPbqEmnj/sv2pFs4xfmOEpyzCsfBHn0K8Pi+ZZ1iUB/lGNK2tRMt0GMCUUKWkwdu9bL0SScHJ3yyfOV/NJMD34n1Vt0Q43qYRF9boogH6pW+4/8Pm4VsJ/357yQKxmV/goSt0ncDuJeIa3z1HE7MGc8dCsz5zNGXFUWMWTuMmVMFfvXf/H7Q4YU3WC+BWV3eX2qWiOVmeqcFFw3W/pKY6ZU1KqfXcs/gQSk1HKNd6LSONXyIsYq02ZFU9sxWPXUEtiuEeVAC7YaIgVvjttFpYOmPXIQZNN2W+FpoJiimc80c/6kJs29SXpyeZfa7C3HZyJpG6I6JnW1jzJIAuAL6IeQxkwDv8weiJXAkJElFikpbFX2+T0gDhO7up5l4QKsZ83vZ4=}
